### ISSUE TITLE
Prep Meetup

### ISSUE THREAD

**Issue by mcansky** [Bnoure/SecondRound#83]
bonjour *

un petit thread de discussion dans une issue pour commencer la préparation du meetup. Quelques points que je relève:
- les messages de commits en français
- le README succinct qui ne me dit pas comment lancer l'app en local
- des petites choses ça et la:
  - https://github.com/Bnoure/SecondRound/blob/master/app/models/booking.rb : pourquoi ne pas utiliser un hash plutot qu'un case ?
- le code commenté laissé dans certaines classes
 
nous devrions discuter un peu plus de ce que fait l'app, et voir s'il y a des points particuliers qui vous intéresse de creuser

**Comment by Bnoure** [comment]
Bonjour , 

-  Je propose d'utiliser cette version plutot https://github.com/Bnoure/2ndRound.git , j'avais passé du temps pour clean deux trois trucs (il doit encore avoir des commentaires) mais il y a le Readme d'installation
